# Site settings
title: ADASTASH
email: adastash@outlook.com
url: https://adastash.net
description: "CARDANO STAKING POOL"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#0d0d0d' #0d0d0d , 171717
  links: '#219ab3'

# Footer settings
footer: ADASTASH

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: https://twitter.com/knoziggeh
  #- title: email
  #  url: https://twitter.com/knoziggeh
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  #- title: github
  #  url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
